#!/usr/bin/env bash

set -e
export DOKKU_ROOT=${DOKKU_ROOT:='/home/git'}

function container_for ( ) {
  APP=$1
  cat $DOKKU_ROOT/$APP/CONTAINER
}

case "$1" in
  console)
    container=$(container_for $2)
    exec docker attach $container
  ;;
  prompt)
    container=$(container_for $2)
    exec docker run -i -t $container /bin/bash
    
  ;;
  console:rebuild)
    container=$(container_for $2)
    exec docker run -i -t $container /bin/bash -c /build/builder
    
  ;;
  version)
    echo git show $DOKKU_ROOT/$2
    git show $DOKKU_ROOT/$2
  ;;
  help)
    cat && cat <<EOF
    console <app>   # tail -f the live app console
    prompt <app>   # live prompt in your app's container
    console:rebuild <app>   # force rebuild of buildpack
EOF
  ;;
esac
cat

